#!/bin/sh

cd `dirname ${BASH_SOURCE[0]}`
echo $PWD

npm install

echo ''
echo 'Testing pac generated by FloraPac'
node ./performanceTest.js ../flora_pac.pac
node ./performanceTest.js ../flora_pac_min.pac

echo ''
echo 'Testing pac generated by FloraPacNJS'
node ./performanceTest.js ./flora_node.pac


echo ''
echo 'Testing pac generated by gfwlist2pac'
node ./performanceTest.js ./gfwlist2pac.pac

echo ''
echo 'Testing pac generated by switchysharp'
node ./performanceTest.js ./switchysharp.pac

echo ''
echo 'Test end'
